language: python
dist: bionic
os: linux
python:
  - "3.11"

jobs:
  include:
    - stage: deploy to prod
      if: branch = master AND type = pull_request
      install:
        - pip install -r requirements.txt
      script:
        - black --check .
        - flake8 .
        - coverage run --source='.' manage.py test
        - python manage.py makemigrations
        - python manage.py migrate
        - coveralls
      deploy:
        provider: elasticbeanstalk
        access_key_id: $AWS_ACCESS_KEY_ID
        secret_access_key: $AWS_SECRET_ACCESS_KEY
        region: "us-west-2"
        app: "6063-polls"
        env: "6063-polls-env"
        bucket_name: "elasticbeanstalk-us-west-2-390402565819"
        on:
          repo: estchang/6063-polls
          branch: master
