language: python
dist: bionic
os: linux
python:
  - "3.11"

jobs:
  include:
    - stage: testing
      if: type = pull_request
      install:
        - pip install -r requirements.txt
      script:
        - pytest
